package com.market.backend.book;

import com.market.backend.domain.Side;

import java.util.ArrayDeque;
import java.util.ArrayList;
import java.util.Comparator;
import java.util.Deque;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.NavigableMap;
import java.util.TreeMap;

/**
 * A single-symbol limit order book with price-time priority matching.
 *
 * <p>Bids are kept in descending price order and asks in ascending price
 * order. Each price level holds a FIFO queue of resting orders so that,
 * within a level, earlier orders are always filled before later ones
 * (strict time priority). Incoming orders that cross the book are matched
 * immediately, potentially against multiple resting orders and multiple
 * price levels; any unfilled remainder of a limit order rests in the book,
 * while any unfilled remainder of a market order is dropped (treated as
 * an immediate-or-cancel order with insufficient liquidity).
 *
 * <p>This class is not thread-safe; callers must serialize access
 * externally if shared across threads.
 */
public final class OrderBook {
    private final String symbol;
    private final NavigableMap<Double, Deque<RestingOrder>> bids = new TreeMap<>(Comparator.reverseOrder());
    private final NavigableMap<Double, Deque<RestingOrder>> asks = new TreeMap<>();
    private final Map<Long, RestingOrder> ordersById = new HashMap<>();
    private final Map<Long, Double> priceById = new HashMap<>();
    private long sequenceGenerator;

    public OrderBook(String symbol) {
        this.symbol = symbol;
    }

    public String symbol() {
        return symbol;
    }

    /**
     * Submits a limit order. It first matches against any crossing resting
     * orders on the opposite side of the book, then rests any unfilled
     * remainder at its limit price.
     *
     * @return the fills generated by this order, in match order (empty if
     *         the order did not cross the book at all)
     */
    public List<Fill> submitLimitOrder(long orderId, Side side, double price, double quantity) {
        if (quantity <= 0.0) {
            throw new IllegalArgumentException("quantity must be positive");
        }
        List<Fill> fills = new ArrayList<>();
        double remaining = match(orderId, side, price, quantity, fills);
        if (remaining > 1e-9) {
            rest(orderId, side, price, remaining);
        }
        return fills;
    }

    /**
     * Submits a market order that matches immediately against the best
     * available prices regardless of limit, sweeping through price levels
     * as needed. Any unfilled remainder (insufficient liquidity) is dropped
     * rather than resting in the book.
     */
    public List<Fill> submitMarketOrder(long orderId, Side side, double quantity) {
        if (quantity <= 0.0) {
            throw new IllegalArgumentException("quantity must be positive");
        }
        List<Fill> fills = new ArrayList<>();
        double unboundedPrice = side == Side.BUY ? Double.POSITIVE_INFINITY : 0.0;
        match(orderId, side, unboundedPrice, quantity, fills);
        return fills;
    }

    /**
     * Cancels a resting order by id. Returns true if it was found and removed.
     */
    public boolean cancel(long orderId) {
        RestingOrder order = ordersById.remove(orderId);
        if (order == null) {
            return false;
        }
        double price = priceById.remove(orderId);
        NavigableMap<Double, Deque<RestingOrder>> book = order.side() == Side.BUY ? bids : asks;
        Deque<RestingOrder> level = book.get(price);
        if (level != null) {
            level.remove(order);
            if (level.isEmpty()) {
                book.remove(price);
            }
        }
        return true;
    }

    public Double bestBid() {
        return bids.isEmpty() ? null : bids.firstKey();
    }

    public Double bestAsk() {
        return asks.isEmpty() ? null : asks.firstKey();
    }

    public Double spread() {
        Double bid = bestBid();
        Double ask = bestAsk();
        return (bid == null || ask == null) ? null : ask - bid;
    }

    public Double midPrice() {
        Double bid = bestBid();
        Double ask = bestAsk();
        return (bid == null || ask == null) ? null : (bid + ask) / 2.0;
    }

    /** Top {@code depth} bid price levels, best price first. */
    public List<PriceLevel> bidLevels(int depth) {
        return levels(bids, depth);
    }

    /** Top {@code depth} ask price levels, best price first. */
    public List<PriceLevel> askLevels(int depth) {
        return levels(asks, depth);
    }

    private List<PriceLevel> levels(NavigableMap<Double, Deque<RestingOrder>> book, int depth) {
        List<PriceLevel> result = new ArrayList<>();
        for (Map.Entry<Double, Deque<RestingOrder>> entry : book.entrySet()) {
            if (result.size() >= depth) {
                break;
            }
            double total = 0.0;
            for (RestingOrder order : entry.getValue()) {
                total += order.remainingQuantity();
            }
            result.add(new PriceLevel(entry.getKey(), total, entry.getValue().size()));
        }
        return result;
    }

    /**
     * Matches an incoming order against the opposite side of the book,
     * generating fills. Returns the unfilled remaining quantity.
     */
    private double match(long takerOrderId, Side side, double limitPrice, double quantity, List<Fill> fills) {
        NavigableMap<Double, Deque<RestingOrder>> opposite = side == Side.BUY ? asks : bids;
        double remaining = quantity;

        while (remaining > 1e-9 && !opposite.isEmpty()) {
            Map.Entry<Double, Deque<RestingOrder>> bestLevel = opposite.firstEntry();
            double levelPrice = bestLevel.getKey();
            if (!crosses(side, limitPrice, levelPrice)) {
                break;
            }
            Deque<RestingOrder> queue = bestLevel.getValue();
            while (remaining > 1e-9 && !queue.isEmpty()) {
                RestingOrder maker = queue.peekFirst();
                double matchQuantity = Math.min(remaining, maker.remainingQuantity());
                maker.reduce(matchQuantity);
                remaining -= matchQuantity;
                fills.add(new Fill(
                        sequenceGenerator++,
                        symbol,
                        maker.orderId(),
                        takerOrderId,
                        side,
                        levelPrice,
                        matchQuantity));
                if (maker.isFilled()) {
                    queue.pollFirst();
                    ordersById.remove(maker.orderId());
                    priceById.remove(maker.orderId());
                }
            }
            if (queue.isEmpty()) {
                opposite.remove(levelPrice);
            }
        }
        return remaining;
    }

    private static boolean crosses(Side takerSide, double takerLimitPrice, double restingPrice) {
        return takerSide == Side.BUY ? takerLimitPrice >= restingPrice : takerLimitPrice <= restingPrice;
    }

    private void rest(long orderId, Side side, double price, double quantity) {
        RestingOrder order = new RestingOrder(orderId, side, price, quantity, sequenceGenerator++);
        NavigableMap<Double, Deque<RestingOrder>> book = side == Side.BUY ? bids : asks;
        book.computeIfAbsent(price, ignored -> new ArrayDeque<>()).addLast(order);
        ordersById.put(orderId, order);
        priceById.put(orderId, price);
    }
}
